# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_df <- function(alpha, lambda, xA) {
    .Call(`_sentometrics_compute_df`, alpha, lambda, xA)
}

compute_sentiment_bigrams <- function(texts, lexicons, how) {
    .Call(`_sentometrics_compute_sentiment_bigrams`, texts, lexicons, how)
}

compute_sentiment_onegrams <- function(texts, lexicons, how) {
    .Call(`_sentometrics_compute_sentiment_onegrams`, texts, lexicons, how)
}

