# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_df <- function(alpha, lambda, xA) {
    .Call(`_sentometrics_compute_df`, alpha, lambda, xA)
}

