# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_df <- function(alpha, lambda, xA) {
    .Call(`_sentometrics_compute_df`, alpha, lambda, xA)
}

compute_sentiment_onegrams <- function(texts, lexicons, how) {
    .Call(`_sentometrics_compute_sentiment_onegrams`, texts, lexicons, how)
}

compute_sentiment_sentence <- function(texts, lexicons, how, hasValenceShifters) {
    .Call(`_sentometrics_compute_sentiment_sentence`, texts, lexicons, how, hasValenceShifters)
}

compute_sentiment_valence <- function(texts, lexicons, how) {
    .Call(`_sentometrics_compute_sentiment_valence`, texts, lexicons, how)
}

fill_NAs <- function(x) {
    .Call(`_sentometrics_fill_NAs`, x)
}

make_frequency_maps <- function(texts, ids, byText) {
    .Call(`_sentometrics_make_frequency_maps`, texts, ids, byText)
}

