<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Intratextual sentiment analysis • sentometrics</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/flatly/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../../bootstrap-toc.css">
<script src="../../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../../pkgdown.css" rel="stylesheet">
<script src="../../pkgdown.js"></script><!-- docsearch --><script src="../../docsearch.js"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.3/docsearch.min.css" integrity="sha256-QOSRU/ra9ActyXkIBbiIB144aDBdtvXBcNc3OTNuX/Q=" crossorigin="anonymous">
<link href="../../docsearch.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script><meta property="og:title" content="Intratextual sentiment analysis">
<meta property="og:description" content="sentometrics">
<meta property="og:image" content="https://sentometricsresearch.github.io/sentometrics/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../../index.html">sentometrics</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.0.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../../articles/sentometrics.html">Get started</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Examples
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li class="dropdown-header">Tutorials</li>
    <li>
      <a href="../../articles/examples/corpus.html">Corpus manipulation</a>
    </li>
    <li>
      <a href="../../articles/examples/sentiment.html">Sentiment computation</a>
    </li>
    <li>
      <a href="../../articles/examples/indexation.html">Index aggregation</a>
    </li>
    <li>
      <a href="../../articles/examples/modeling.html">Modeling</a>
    </li>
    <li class="divider">
    <li class="dropdown-header">Applications</li>
    <li>
      <a href="../../articles/applications/epu.html">Creating EPU indices</a>
    </li>
    <li>
      <a href="../../articles/applications/vix.html">Predicting the VIX index</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Contributions
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../../articles/contributions/gopress.html">Analyzing Gopress data</a>
    </li>
    <li>
      <a href="../../articles/contributions/isa.html">Intratextual sentiment analysis</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    News
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../../articles/development.html">Development</a>
    </li>
    <li>
      <a href="../../news/index.html">Releases</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/SentometricsResearch/sentometrics/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
<form class="navbar-form navbar-right hidden-xs hidden-sm" role="search">
        <div class="form-group">
          <input type="search" class="form-control" name="search-input" id="search-input" placeholder="Search..." aria-label="Search for..." autocomplete="off">
</div>
      </form>
      
    </div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="isa_files/header-attrs-2.10/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Intratextual sentiment analysis</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/SentometricsResearch/sentometrics/blob/master/vignettes/contributions/isa.Rmd"><code>vignettes/contributions/isa.Rmd</code></a></small>
      <div class="hidden name"><code>isa.Rmd</code></div>

    </div>

    
    
<p>Tutorial contributed by <a href="mailto:delmarcelle.olivier@gmail.com">Olivier Delmarcelle</a> (PhD student, Ghent University).</p>
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>The <strong><code>sentometrics</code></strong> package introduces simple functions to quickly compute the sentiment of texts within a corpus. This easy-to-use approach does not prevent more advanced analysis, and the <strong><code>sentometrics</code></strong> functions remain a solid choice for cutting-edge research. This tutorial will present how to go beyond the basic <strong><code>sentometrics</code></strong> settings in order to analyse the intratextual sentiment structure of texts.</p>
<div id="intratextual-sentiment-structure" class="section level3">
<h3 class="hasAnchor">
<a href="#intratextual-sentiment-structure" class="anchor"></a>Intratextual sentiment structure</h3>
<p>Does the position of positive and negative words within a text matter? This question is investigated by <a href="https://doi.org/10.1111/fima.12219">Boudt &amp; Thewissen (2019)</a> during their research regarding sentiment implied by CEO letters. Based on a large dataset of letters, they analyze how sentiment-bearing words are positioned within the text. They find that CEOs tend to emphasize sentiment at the beginning and the end of their letter, in the hopes of leaving a positive impression to the reader.</p>
<p>Their results confirm generally accepted theories of linguistics saying that readers remember best the first (primacy effect) and the last (recency effect) portions of a text, and that the end of the text contributes the most to the reader’s final feeling.</p>
<p>One can wonder whether other types of texts follow a similar structure? Indeed, the world is full of different text media, from Twitter posts to news articles, and most of them are less cautiously written than CEO letters. Let’s investigate together some news data with the help of the <strong><code>sentometrics</code></strong> package!</p>
</div>
<div id="learning-outcomes" class="section level3">
<h3 class="hasAnchor">
<a href="#learning-outcomes" class="anchor"></a>Learning outcomes</h3>
<p>As part of this tutorial, you will learn how to:</p>
<ul>
<li>Decompose your texts into <em>bins</em> (typically equal-sized containers of words) or sentences.</li>
<li>Compute sentiment with a variety of weighting schemes.</li>
<li>Create and use your own weighting scheme for a classification task.</li>
</ul>
</div>
</div>
<div id="picking-up-the-instruments" class="section level2">
<h2 class="hasAnchor">
<a href="#picking-up-the-instruments" class="anchor"></a>Picking up the instruments</h2>
<p>We first prepare some of the key inputs, the instruments so to speak, for the analysis. We start off with loading the required packages.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/leeper/rio">"rio"</a></span><span class="op">)</span>           <span class="co"># package for extracting data from GitHub</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://r-datatable.com">"data.table"</a></span><span class="op">)</span>    <span class="co"># package bringing in the data.table machinery</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://quanteda.io">"quanteda"</a></span><span class="op">)</span>      <span class="co"># package useful for text and corpus manipulation</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://sentometrics-research.com/sentometrics/">"sentometrics"</a></span><span class="op">)</span>  <span class="co"># package containing sentiment computation tools</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/trinker/lexicon">"lexicon"</a></span><span class="op">)</span>       <span class="co"># package with multiple lexicons</span></code></pre></div>
<p>In this tutorial, we will use a slight variation from the built-in <code>usnews</code> object from the <strong><code>sentometrics</code></strong> package. We would like to compare our computed sentiment measure against some benchmark, but the built-in <code>usnews</code> does not include one. Fortunately, we processed a new dataset <code>usnews2</code> containing a benchmark just for you! It can be retrieved directly from GitHub using the <strong><code>rio</code></strong> package.</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">usnews2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/rio/man/import.html">import</a></span><span class="op">(</span><span class="st">"https://raw.githubusercontent.com/odelmarcelle/public/master/usnews2/usnews2.RData"</span><span class="op">)</span>
<span class="va">usnews2</span><span class="op">[</span>, <span class="st">"id"</span> <span class="op">:=</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="va">id</span><span class="op">)</span><span class="op">]</span></code></pre></div>
<p>The embedded variable <code>s</code> indicates whether the news is more positive or negative, based on expert opinion. We are going to try to predict this value at the end of the tutorial.</p>
<p>We can already prepare a <code>sento_corpus</code> and a <code>sento_lexicon</code> for the sentiment computation. For the <code>sento_corpus</code>, we will also create a <code>dummyFeature</code> that has the value 1 for the entire corpus. The sentiment computations are multiplied by the features. This <code>dummyFeature</code> is created by default when there is no feature available. Finally, we remove the original feature <code>s</code> from the <code>sento_corpus</code>, as we do not need it in the sentiment computation.</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">usnews2Sento</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/sento_corpus.html">sento_corpus</a></span><span class="op">(</span><span class="va">usnews2</span><span class="op">)</span> <span class="co"># note that the feature 's' is automatically rescaled to [0, 1]</span>
<span class="va">usnews2Sento</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/add_features.html">add_features</a></span><span class="op">(</span><span class="va">usnews2Sento</span>, <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>dummyFeature <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">usnews2Sento</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://quanteda.io/reference/docvars.html">docvars</a></span><span class="op">(</span><span class="va">usnews2Sento</span>, <span class="st">"s"</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="cn">NULL</span> <span class="co"># removing the feature</span></code></pre></div>
<p>We will use a single lexicon for this analysis, the combined Jockers &amp; Rinker lexicon, obtained from the <strong><code>lexicon</code></strong> package. However, we will prepare a second and different version of this lexicon where the sentiment assigned to words are all positive, regardless of their original signs. This second lexicon will be useful to better detect the sentiment intensity conveyed.</p>
<p>We use the <code>data.table</code> operator <code>[]</code> to create the second lexicon in a very efficient way. Most <strong><code>sentometrics</code></strong> objects are based upon <code>data.table</code> and this allows performing complex data transformations. If this is the first time you are seeing the <code>data.table</code> way of using <code>[]</code>, we recommend you to have a look at their introductory <a href="https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html">vignette</a> and enjoy this powerful tool!</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lex</span> <span class="op">&lt;-</span> <span class="fu">lexicon</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/lexicon/man/hash_sentiment_jockers_rinker.html">hash_sentiment_jockers_rinker</a></span>

<span class="va">sentoLexicon</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/sento_lexicons.html">sento_lexicons</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>baseLex <span class="op">=</span> <span class="va">lex</span>,
                                    absoluteLex <span class="op">=</span> <span class="va">lex</span><span class="op">[</span>, <span class="fu">.</span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span><span class="op">)</span><span class="op">]</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">sentoLexicon</span>, <span class="va">head</span><span class="op">)</span></code></pre></div>
<pre><code>## $baseLex
##              x     y
## 1:     abandon -0.75
## 2:   abandoned -0.50
## 3:   abandoner -0.25
## 4: abandonment -0.25
## 5:    abandons -1.00
## 6:    abducted -1.00
## 
## $absoluteLex
##              x    y
## 1:     abandon 0.75
## 2:   abandoned 0.50
## 3:   abandoner 0.25
## 4: abandonment 0.25
## 5:    abandons 1.00
## 6:    abducted 1.00</code></pre>
</div>
<div id="a-review-of-sentiment-computation-with-sentometrics" class="section level2">
<h2 class="hasAnchor">
<a href="#a-review-of-sentiment-computation-with-sentometrics" class="anchor"></a>A review of sentiment computation with <strong><code>sentometrics</code></strong>
</h2>
<p>The <code><a href="../../reference/compute_sentiment.html">compute_sentiment()</a></code> function offers the core of the textual sentiment computation with <strong><code>sentometrics</code></strong>. Before jumping to intraxtual sentiment calculation, let us review the different computation settings to really understand what is happening.</p>
<div id="from-words-to-document-sentiment" class="section level3">
<h3 class="hasAnchor">
<a href="#from-words-to-document-sentiment" class="anchor"></a>From words to document sentiment</h3>
<p>When using the default settings (i.e., only specifying the <code>how</code> argument), the sentiment for each word within a text will be determined according to the provided lexicons. This word-level sentiment is then aggregated using the method defined by the <code>how</code> argument, aggregating up to the document level to form a sentiment value for the document.</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sentiment</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/compute_sentiment.html">compute_sentiment</a></span><span class="op">(</span><span class="va">usnews2Sento</span>, <span class="va">sentoLexicon</span>, how <span class="op">=</span> <span class="st">"proportional"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">sentiment</span><span class="op">)</span></code></pre></div>
<pre><code>##           id       date word_count baseLex--dummyFeature absoluteLex--dummyFeature
## 1: 830982098 1971-01-12        413          -0.009927361                0.09225182
## 2: 830983504 1971-08-04        171          -0.007602339                0.03859649
## 3: 830985611 1971-08-24        280           0.028750000                0.04839286
## 4: 830985462 1972-01-28        123           0.041869919                0.09634146
## 5: 830982094 1973-02-15        132          -0.028409091                0.11856061
## 6: 830985122 1973-05-31        144           0.046527778                0.06805556</code></pre>
<p>In this case, the <code>how = "proportional"</code> option sums word-level sentiment, and then divides by the number of words in a document. The different settings for <code>how</code> can be accessed using the <code><a href="../../reference/get_hows.html">get_hows()</a></code> function. We are going to present the use of a more complex setting at the end of this tutorial.</p>
</div>
<div id="from-words-to-sentences-sentiment-with-do-sentence-true" class="section level3">
<h3 class="hasAnchor">
<a href="#from-words-to-sentences-sentiment-with-do-sentence-true" class="anchor"></a>From words to sentences sentiment with <code>do.sentence = TRUE</code>
</h3>
<p>A drastic change in the behaviour of <code><a href="../../reference/compute_sentiment.html">compute_sentiment()</a></code> can be induced by specifying <code>do.sentence = TRUE</code> in the function call. If true, the output of <code>compute_sentiment</code> will no longer return a sentiment value for each document, but each sentence. Sentiment values within each sentence are still computed using the method provided in the <code>how</code> argument, but the function stops there.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sentiment</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/compute_sentiment.html">compute_sentiment</a></span><span class="op">(</span><span class="va">usnews2Sento</span>, <span class="va">sentoLexicon</span>, how <span class="op">=</span> <span class="st">"proportional"</span>, do.sentence <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">sentiment</span><span class="op">)</span></code></pre></div>
<pre><code>##           id sentence_id       date word_count baseLex--dummyFeature absoluteLex--dummyFeature
## 1: 830982098           1 1971-01-12         39          -0.041025641                0.06666667
## 2: 830982098           2 1971-01-12         14          -0.035714286                0.03571429
## 3: 830982098           3 1971-01-12         21          -0.076190476                0.07619048
## 4: 830982098           4 1971-01-12         30          -0.076666667                0.14333333
## 5: 830982098           5 1971-01-12         13          -0.096153846                0.18846154
## 6: 830982098           6 1971-01-12         22          -0.006818182                0.09772727</code></pre>
<p>The new column <code>sentence_id</code> in the output is used to identify the sentences of a single document. This result can be used as-is for analysis at the sentence level, or sentences sentiment can be aggregated to obtain documents sentiment, as in the default setting. One way to aggregate sentences sentiment up to documents sentiment is to use the <code><a href="https://rdrr.io/r/stats/aggregate.html">aggregate()</a></code> method of <strong><code>sentometrics</code></strong>.</p>
</div>
<div id="a-trick-with-bins-in-a-list-and-the-do-sentence-tokens-arguments" class="section level3">
<h3 class="hasAnchor">
<a href="#a-trick-with-bins-in-a-list-and-the-do-sentence-tokens-arguments" class="anchor"></a>A trick with bins in a list and the <code>do.sentence</code> &amp; <code>tokens</code> arguments</h3>
<p>Analyzing the sentiment of individual sentences is already a nice approach to observe intra-document sentiment, but sometimes it is better to define a custom container for which sentiment is going to be computed. This is the approach used by <a href="https://doi.org/10.1111/fima.12219">Boudt &amp; Thewissen (2019)</a>, where they define <em>bins</em>, equal-sized containers of texts. The idea is to divide a document into equal-sized portion and to analyse each of them independently. Say we decide to split a document of 200 words into 10 <em>bins</em>. To do so, we store the first 20 words in the first <em>bin</em>, words 21 to 40 in the second <em>bin</em>, and so on… This way, each <em>bin</em> will account for 10% of the text. By repeating the procedure for all texts of a corpus, we can easily compare specific text portions (e.g., the first 10%) between multiple documents.</p>
<p>Time to split our documents into sets of <em>bins</em>. The first step is to obtain a vector of characters for each document. This is done easily with the <code>tokens</code> function from the <strong><code>quanteda</code></strong> (remember that <strong><code>sentometrics</code></strong> objects are also based on <strong><code>quanteda</code></strong>, letting us free to use most functions from this package).</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">usnews2Toks</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://quanteda.io/reference/tokens.html">tokens</a></span><span class="op">(</span><span class="va">usnews2Sento</span>, remove_punct <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="va">usnews2Toks</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://quanteda.io/reference/tokens_tolower.html">tokens_tolower</a></span><span class="op">(</span><span class="va">usnews2Toks</span><span class="op">)</span> <span class="co"># changing all letters to lowercase is optional but recommended</span></code></pre></div>
<p>We now have a list of character vectors, one for each document. The second step is to split each of these vectors into a list of vectors, one vector representing one <em>bin</em>. The final structure will look like:</p>
<ul>
<li>Document 1
<ul>
<li>
<em>Bin</em> 1: “word1”, “word2”, …</li>
<li>
<em>Bin</em> 2: “word1”, “word2”, …</li>
<li>…</li>
<li>
<em>Bin</em> K: “word1”, “word2”, …</li>
</ul>
</li>
<li>Document 2
<ul>
<li>
<em>Bin</em> 1: “word1”, “word2”, …</li>
<li>
<em>Bin</em> 2: “word1”, “word2”, …</li>
<li>…</li>
<li>
<em>Bin</em> K: “word1”, “word2”, …</li>
</ul>
</li>
<li>…</li>
</ul>
<p>This can be done with the help of the convenient function <code><a href="https://rdrr.io/r/parallel/splitIndices.html">parallel::splitIndices()</a></code>. Usually intended to split tasks in a parallel computing setup, this function does exactly what we need: it splits a vector <code>1:N</code> into a list of <code>k</code> vectors. We use it to split the indices of each character vector in <code>usnews2Toks</code>.</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nBins</span> <span class="op">&lt;-</span> <span class="fl">10</span>

<span class="va">usnews2Bins</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">as.list</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">nBins</span><span class="op">)</span>
<span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_along</a></span><span class="op">(</span><span class="va">usnews2Toks</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span>
  <span class="va">usnews2Bins</span><span class="op">[[</span><span class="va">i</span><span class="op">]</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="fu">parallel</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/r/parallel/splitIndices.html">splitIndices</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">usnews2Toks</span><span class="op">[[</span><span class="va">i</span><span class="op">]</span><span class="op">]</span><span class="op">)</span>, <span class="va">nBins</span><span class="op">)</span>,
                             <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="va">usnews2Toks</span><span class="op">[[</span><span class="va">i</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="va">x</span><span class="op">]</span><span class="op">)</span>
<span class="op">}</span>
<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">usnews2Bins</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">usnews2Toks</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">usnews2Bins</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span>, <span class="fl">2</span><span class="op">)</span></code></pre></div>
<pre><code>## [[1]]
##  [1] "regardless"     "of"             "any"            "mitigating"     "qualifications"
##  [6] "that"           "may"            "be"             "read"           "into"          
## [11] "it"             "the"            "unemployment"   "of"             "6"             
## [16] "per"            "cent"           "of"             "the"            "national"      
## [21] "labor"          "force"          "in"             "december"       "is"            
## [26] "a"              "sobering"       "commentary"     "on"             "the"           
## [31] "economic"       "transition"     "through"        "which"          "the"           
## [36] "united"         "states"         "is"             "passing"        "undoubtedly"   
## [41] "it"             "does"          
## 
## [[2]]
##  [1] "reflect"      "in"           "part"         "the"          "winding"      "down"        
##  [7] "of"           "the"          "war"          "in"           "vietnam"      "in"          
## [13] "larger"       "measure"      "it"           "is"           "a"            "product"     
## [19] "of"           "the"          "economic"     "slowdown"     "deliberately" "brought"     
## [25] "about"        "to"           "curb"         "an"           "alarming"     "rise"        
## [31] "in"           "inflation"    "the"          "specific"     "cause"        "in"          
## [37] "any"          "particular"   "case"         "will"         "not"          "lessen"</code></pre>
<p>Looking good! The last step is now to get the sentiment value for each <em>bin</em>. Implementing this approach with <code><a href="../../reference/compute_sentiment.html">compute_sentiment()</a></code> requires to cheat a little! We will trick <code><a href="../../reference/compute_sentiment.html">compute_sentiment()</a></code> into believing that <em>bins</em> are actually sentences. This is done using the <code>tokens</code> argument in the function call and passing to it the <code>usnews2Bins</code> object we just created. The function will treat each character vector in <code>usnews2Bins</code> as a sentence and compute sentiment for it.</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sentiment</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/compute_sentiment.html">compute_sentiment</a></span><span class="op">(</span><span class="va">usnews2Sento</span>, <span class="va">sentoLexicon</span>, how <span class="op">=</span> <span class="st">"proportional"</span>, do.sentence <span class="op">=</span> <span class="cn">TRUE</span>,
                               tokens <span class="op">=</span> <span class="va">usnews2Bins</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">sentiment</span><span class="op">)</span></code></pre></div>
<pre><code>##           id sentence_id       date word_count baseLex--dummyFeature absoluteLex--dummyFeature
## 1: 830982098           1 1971-01-12         42          -0.038095238                0.06190476
## 2: 830982098           2 1971-01-12         42          -0.055952381                0.05595238
## 3: 830982098           3 1971-01-12         42          -0.072619048                0.19642857
## 4: 830982098           4 1971-01-12         42          -0.027380952                0.06309524
## 5: 830982098           5 1971-01-12         42          -0.001190476                0.12976190
## 6: 830982098           6 1971-01-12         41           0.034146341                0.03902439</code></pre>
<p>In this case, the <code>sentence_id</code> simply refers to the number of the <em>bin</em>. Let’s now see what we can do with the <em>bins</em> we just computed.</p>
</div>
</div>
<div id="exposing-the-intratextual-sentiment-structure-with-bins" class="section level2">
<h2 class="hasAnchor">
<a href="#exposing-the-intratextual-sentiment-structure-with-bins" class="anchor"></a>Exposing the intratextual sentiment structure with bins</h2>
<p>In their analysis of CEO letters, <a href="https://doi.org/10.1111/fima.12219">Boudt &amp; Thewissen (2019)</a> identified a clear intratextual sentiment structure. CEOs tend to deliberately emphasize sentiment at the beginning and at the end of their letter, and also typically leave a positive message at the end. News articles are different from CEO letters so we cannot presuppose to find a similar structure. However, based on our knowledge of news, it sounds reasonable to believe that news articles use stronger sentiment in their headlines to attract readers. Our <em>bins</em> allow investigating this hypothesis!</p>
<div id="absolute-sentiment" class="section level3">
<h3 class="hasAnchor">
<a href="#absolute-sentiment" class="anchor"></a>Absolute sentiment</h3>
<p>We expect that the first <em>bin</em> in each article has on average more sentiment than the rest of the text. Since news can either be positive or negative, it will easier to identify sentiment intensity using the absolute value lexicon prepared earlier. This way, we avoid the cancelling effect between positive and negative sentiment. Plotting the mean sentiment values for each <em>bin</em> across documents can give us some insight on the intratextual structure. Once again, we rely on <code>data.table</code>’s <code>[]</code> operator to easily group sentiment values per <code>sentence_id</code> (remember, these represent the <em>bin</em> numbers!). In addition to this, a boxplot is useful to ensure that the mean sentiment is not driven by extreme outliers.</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">sentiment</span><span class="op">[</span>, <span class="fu">.</span><span class="op">(</span>s <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">`absoluteLex--dummyFeature`</span><span class="op">)</span><span class="op">)</span>, by <span class="op">=</span> <span class="va">sentence_id</span><span class="op">]</span>, type <span class="op">=</span> <span class="st">"l"</span>,
     ylab <span class="op">=</span> <span class="st">"Mean absolute sentiment"</span>, xlab <span class="op">=</span> <span class="st">"Bin"</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="va">sentiment</span><span class="op">$</span><span class="va">`absoluteLex--dummyFeature`</span> <span class="op">~</span> <span class="va">sentiment</span><span class="op">$</span><span class="va">sentence_id</span>, ylab <span class="op">=</span> <span class="st">"Absolute sentiment"</span>, 
        xlab <span class="op">=</span> <span class="st">"Bin"</span>, outline <span class="op">=</span> <span class="cn">FALSE</span>, range <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span></code></pre></div>
<p><img src="isa_files/figure-html/unnamed-chunk-10-1.png" width="1152"></p>
<p>We can see that the first two <em>bins</em> of articles tend to show a larger absolute sentiment on average. This gives some credit to our initial hypothesis that news headlines contain more sentiment.</p>
</div>
<div id="herfindahl-hirschman-index" class="section level3">
<h3 class="hasAnchor">
<a href="#herfindahl-hirschman-index" class="anchor"></a>Herfindahl-Hirschman index</h3>
<p>Another way to study the intratextual sentiment structure is to compute the Herfindahl-Hirschman index across all documents. This is a popular index of concentration, mainly used in measuring competition between firms on a given market. A value close to 0 indicates large dispersion between <em>bins</em> while a value of 1 indicates that all sentiment is found in a single <em>bin</em>. The formula to compute the index of a single document is:</p>
<p><span class="math display">\[H = \sum_{b=1}^{B} s_b^2\]</span> where <span class="math inline">\(b\)</span> are <em>bin</em> indexes and <span class="math inline">\(s\)</span> the proportion of the document sentiment found in a single <em>bin</em>. Using <code>data.table</code>, we can easily compute the index for the whole set of documents.</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">herfindahl</span> <span class="op">&lt;-</span> <span class="va">sentiment</span><span class="op">[</span>, <span class="fu">.</span><span class="op">(</span>s <span class="op">=</span> <span class="va">`absoluteLex--dummyFeature`</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">`absoluteLex--dummyFeature`</span><span class="op">)</span><span class="op">)</span>, by <span class="op">=</span> <span class="va">id</span><span class="op">]</span>
<span class="va">herfindahl</span> <span class="op">&lt;-</span> <span class="va">herfindahl</span><span class="op">[</span>, <span class="fu">.</span><span class="op">(</span>h <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">s</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span>, by <span class="op">=</span> <span class="va">id</span><span class="op">]</span>
<span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">herfindahl</span><span class="op">$</span><span class="va">h</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.1445487</code></pre>
<p>A result that shows there is concentration toward some <em>bins</em>! Note that this result is heavily dependent on the number of <em>bins</em> considered. Only index values computed with the same number of <em>bins</em> should be compared. In case sentiment were uniformly positioned within the text, the Herfindahl-Hirschman index value would be as shown belown.</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/data.table.html">data.table</a></span><span class="op">(</span>id <span class="op">=</span> <span class="va">sentiment</span><span class="op">$</span><span class="va">id</span>, s <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">sentiment</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>

<span class="va">herfindahl</span> <span class="op">&lt;-</span> <span class="va">x</span><span class="op">[</span>, <span class="fu">.</span><span class="op">(</span>s <span class="op">=</span> <span class="va">s</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">s</span><span class="op">)</span><span class="op">)</span>, by <span class="op">=</span> <span class="va">id</span><span class="op">]</span>
<span class="va">herfindahl</span> <span class="op">&lt;-</span> <span class="va">herfindahl</span><span class="op">[</span>, <span class="fu">.</span><span class="op">(</span>h <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">s</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span>, by <span class="op">=</span> <span class="va">id</span><span class="op">]</span>
<span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">herfindahl</span><span class="op">$</span><span class="va">h</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.1</code></pre>
</div>
</div>
<div id="computing-sentiment-with-different-weights" class="section level2">
<h2 class="hasAnchor">
<a href="#computing-sentiment-with-different-weights" class="anchor"></a>Computing sentiment with different weights</h2>
<p>The <strong><code>sentometrics</code></strong> package brings a lot of different weighting methods to compute sentiment and aggregate them into document-level sentiment and time series. These weighting methods can be accessed with the function <code><a href="../../reference/get_hows.html">get_hows()</a></code>.</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../../reference/get_hows.html">get_hows</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## $words
## [1] "counts"                 "proportional"           "proportionalPol"       
## [4] "proportionalSquareRoot" "UShaped"                "inverseUShaped"        
## [7] "exponential"            "inverseExponential"     "TFIDF"                 
## 
## $docs
## [1] "equal_weight"        "proportional"        "inverseProportional" "exponential"        
## [5] "inverseExponential" 
## 
## $time
## [1] "equal_weight" "almon"        "beta"         "linear"       "exponential"  "own"</code></pre>
<p>So far, we’ve been using the <code>proportional</code> method from the <code>$words</code> set. The <code>$words</code> set contains the valid options for the <code>hows</code> argument of <code><a href="../../reference/compute_sentiment.html">compute_sentiment()</a></code>. The other two sets are used within the <code><a href="https://rdrr.io/r/stats/aggregate.html">aggregate()</a></code> function, to respectively aggregate sentences sentiment into documents or document sentiment into time series.</p>
<p>With our earlier computation of sentiment using <code>do.sentences = TRUE</code>, we computed sentiment for sentences and <em>bins</em>. Now, for our next application, we need to aggregate these sentences and <em>bins</em> sentiment into documents sentiment. One option is to <code><a href="https://rdrr.io/r/stats/aggregate.html">aggregate()</a></code> using one of the methods shown above. Note the use of <code>do.full = FALSE</code> to stop the aggregation at the document level (otherwise, it would directly aggregate up to a time series).</p>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docsSentiment</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="va">sentiment</span>, <span class="fu"><a href="../../reference/ctr_agg.html">ctr_agg</a></span><span class="op">(</span>howDocs <span class="op">=</span> <span class="st">"equal_weight"</span><span class="op">)</span>, do.full <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>sentiment <span class="op">=</span> <span class="va">sentiment</span>, docsSentiment <span class="op">=</span> <span class="va">docsSentiment</span><span class="op">)</span>, <span class="va">head</span><span class="op">)</span></code></pre></div>
<pre><code>## $sentiment
##           id sentence_id       date word_count baseLex--dummyFeature absoluteLex--dummyFeature
## 1: 830982098           1 1971-01-12         42          -0.038095238                0.06190476
## 2: 830982098           2 1971-01-12         42          -0.055952381                0.05595238
## 3: 830982098           3 1971-01-12         42          -0.072619048                0.19642857
## 4: 830982098           4 1971-01-12         42          -0.027380952                0.06309524
## 5: 830982098           5 1971-01-12         42          -0.001190476                0.12976190
## 6: 830982098           6 1971-01-12         41           0.034146341                0.03902439
## 
## $docsSentiment
##           id       date word_count baseLex--dummyFeature absoluteLex--dummyFeature
## 1: 830982098 1971-01-12        419          -0.009680604                0.09080720
## 2: 830983504 1971-08-04        174          -0.014836601                0.07620915
## 3: 830985611 1971-08-24        282           0.025615764                0.04232759
## 4: 830985462 1972-01-28        128           0.044871795                0.09836182
## 5: 830982094 1973-02-15        149          -0.028428571                0.10185714
## 6: 830985122 1973-05-31        146           0.045690476                0.06721429</code></pre>
<p>But as we have seen, some <em>bins</em> are more likely to present strong sentiment values than other, notably the first <em>bin</em> containing the headline of a news article. In this case, an equal weighting between <em>bins</em> will give as much importance to the inflated headline as the rest of the text. Maybe would it better to give less importance to the first <em>bin</em> instead, which would then limit its effect on the final document sentiment?</p>
<div id="specifying-your-own-weights" class="section level3">
<h3 class="hasAnchor">
<a href="#specifying-your-own-weights" class="anchor"></a>Specifying your own weights</h3>
<p>This is exactly the situation where we would like to test a specific weighting scheme! Say that instead of giving 10% importance to each <em>bin</em> in the document sentiment computation, we would give only about 5% importance to the first one and share the rest between the remaining <em>bins</em>. Sadly, <strong><code>sentometrics</code></strong> does not directly provide us with the tool for this kind of computation, we will need to create our weighting scheme and aggregate by hands. Luckily, the use of <code>data.table</code> makes these customisations painless.</p>
<p>First, we define customized <em>bin</em> weights.</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">w</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span> <span class="op">/</span> <span class="op">(</span><span class="va">nBins</span> <span class="op">-</span> <span class="fl">0.5</span><span class="op">)</span>, <span class="va">nBins</span><span class="op">)</span>
<span class="va">w</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">&lt;-</span>  <span class="va">w</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">*</span> <span class="fl">0.5</span>

<span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>sum <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">w</span><span class="op">)</span>, w <span class="op">=</span> <span class="va">w</span><span class="op">)</span></code></pre></div>
<pre><code>## $sum
## [1] 1
## 
## $w
##  [1] 0.05263158 0.10526316 0.10526316 0.10526316 0.10526316 0.10526316 0.10526316 0.10526316
##  [9] 0.10526316 0.10526316</code></pre>
<p>Second, we create a function to aggregate <em>bins</em> based on our customized weights. This is nothing more than the sum of element-wise vector multiplications.</p>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">aggregate_bins</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span>, <span class="va">w</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">x</span> <span class="op">*</span> <span class="va">w</span><span class="op">)</span>

<span class="fu">aggregate_bins</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 1.75</code></pre>
<p>Third, we need to aggregate by hand using this weighting scheme, taking advantage of <code>data.table</code> operations. Things are slightly more complex here.</p>
<p>As we are aggregating for each document, we set <code>by = id</code> to specify the groups for the other operations. There is only one <code>date</code> for each <code>id</code>, so using <code>by = .(id, date)</code> simply keeps the <code>date</code> column in the output.</p>
<p>Concerning the intra-groups aggregation (i.e., aggregating the <em>bins</em> of each document), there are two operations to perform. On one hand, we compute the sum of <code>word_count</code> in each <em>bin</em>, to obtain the number of words in the document. On the other hand, we apply the function <code>aggregate_bins()</code> to a number of columns. <code>.SD</code> is a special symbol of data.table that specify a subset on which an operation should be performed. In this case, the subset represented by <code>.SD</code> is the columns stored in <code>.SDcols</code>. In simple words, this will apply the <code>aggregate_bins()</code> function to each column, starting from column 5 (because columns 1 to 4 are <code>id</code>, <code>date</code>, <code>sentence_id</code> and <code>word_count</code>).</p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docsSentiment</span> <span class="op">&lt;-</span> <span class="va">sentiment</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>word_count <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">word_count</span><span class="op">)</span>, 
                               <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">.SD</span>, <span class="va">aggregate_bins</span>, w <span class="op">=</span> <span class="va">w</span><span class="op">)</span><span class="op">)</span>,
                           by <span class="op">=</span> <span class="fu">.</span><span class="op">(</span><span class="va">id</span>, <span class="va">date</span><span class="op">)</span>,
                           .SDcols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/utils/head.html">tail</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">sentiment</span><span class="op">)</span>, <span class="op">-</span><span class="fl">4</span><span class="op">)</span><span class="op">]</span>

<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">docsSentiment</span><span class="op">)</span></code></pre></div>
<pre><code>##           id       date word_count baseLex--dummyFeature absoluteLex--dummyFeature
## 1: 830982098 1971-01-12        419          -0.008185097                0.09232838
## 2: 830983504 1971-08-04        174          -0.005615755                0.03791710
## 3: 830985611 1971-08-24        282           0.022857791                0.04314558
## 4: 830985462 1972-01-28        128           0.032523617                0.08792173
## 5: 830982094 1973-02-15        149          -0.031328321                0.10300752
## 6: 830985122 1973-05-31        146           0.047218045                0.06812030</code></pre>
<p>On top of that, the output of this transformation is still a correct <strong><code>sentometrics</code></strong> <code>sentiment</code> object!</p>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">docsSentiment</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "sentiment"  "data.table" "data.frame"</code></pre>
</div>
<div id="application-to-news-sentiment-prediction" class="section level3">
<h3 class="hasAnchor">
<a href="#application-to-news-sentiment-prediction" class="anchor"></a>Application to news sentiment prediction</h3>
<p>Next, we put all of this in a concrete example. We’ve been using a modified dataset <code>usnews2</code> since the beginning because we wanted to have a variable identifying whether the document is positive or negative. Our goal is now to try to predict this value.</p>
<p>To do so, we will consider 4 different approaches, in the form of four different weighting methods. We will study which weighting is the best to predict document-level sentiment. The four weighting methods are:</p>
<ul>
<li>The default weighting based on word frequencies, regardless of the position.</li>
<li>A U-shaped weighting of words, where words at the beginning or end of the text are given more weights.</li>
<li>A sentence weighting, where word sentiment is proportionally weighted up to a sentence sentiment level, then sentences are aggregated with an equal weighting to obtain the document sentiment.</li>
<li>The <em>bin</em> based approach, where word sentiment is proportionally weighted up to <em>bin</em> sentiment level, then <em>bins</em> are aggregated with our custom weights giving the first <em>bin</em> half the weight and the other <em>bins</em> sharing the rest.</li>
</ul>
<p>The U-shaped weighting is a weighting method for words, as we can learn from <code><a href="../../reference/get_hows.html">get_hows()</a></code>. This scheme gives more weight to the beginning and end of a text. Its exact formulation can be found in the appendix of the <a href="https://doi.org/10.2139/ssrn.3067734">sentometrics vignette</a>, along with the other available weightings. This weighting scheme can be visualized as follows:</p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Qd</span> <span class="op">&lt;-</span> <span class="fl">200</span> <span class="co"># number of words in the documents</span>
<span class="va">i</span> <span class="op">&lt;-</span> <span class="fl">1</span><span class="op">:</span><span class="va">Qd</span> <span class="co"># word position</span>
<span class="va">ushaperaw</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">i</span> <span class="op">-</span> <span class="op">(</span><span class="va">Qd</span><span class="op">+</span><span class="fl">1</span><span class="op">)</span> <span class="op">/</span> <span class="fl">2</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span>
<span class="va">ushape</span> <span class="op">&lt;-</span> <span class="va">ushaperaw</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">ushaperaw</span><span class="op">)</span> <span class="co"># normalized</span>

<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">ushape</span>, type <span class="op">=</span> <span class="st">'l'</span>, ylab <span class="op">=</span> <span class="st">"Weight"</span>, xlab <span class="op">=</span> <span class="st">"Word position index"</span>, main <span class="op">=</span> <span class="st">"U-shaped weighting scheme"</span><span class="op">)</span></code></pre></div>
<p><img src="isa_files/figure-html/unnamed-chunk-19-1.png" width="700"></p>
<p>Let’s compute sentiment with the four different weighting schemes. We store the results in the list <code>sentimentValues</code>.</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sentimentValues</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="op">)</span>

<span class="va">sentimentValues</span><span class="op">$</span><span class="va">default</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/compute_sentiment.html">compute_sentiment</a></span><span class="op">(</span><span class="va">usnews2Sento</span>, <span class="va">sentoLexicon</span>, how <span class="op">=</span> <span class="st">"proportional"</span><span class="op">)</span>
<span class="va">sentimentValues</span><span class="op">$</span><span class="va">uShaped</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/compute_sentiment.html">compute_sentiment</a></span><span class="op">(</span><span class="va">usnews2Sento</span>, <span class="va">sentoLexicon</span>, how <span class="op">=</span> <span class="st">"UShaped"</span><span class="op">)</span>
<span class="va">sentimentValues</span><span class="op">$</span><span class="va">sentences</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/compute_sentiment.html">compute_sentiment</a></span><span class="op">(</span><span class="va">usnews2Sento</span>, <span class="va">sentoLexicon</span>, how <span class="op">=</span> <span class="st">"proportional"</span>, 
                                               do.sentence <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="va">sentimentValues</span><span class="op">$</span><span class="va">bins</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/compute_sentiment.html">compute_sentiment</a></span><span class="op">(</span><span class="va">usnews2Sento</span>, <span class="va">sentoLexicon</span>, tokens <span class="op">=</span> <span class="va">usnews2Bins</span>, 
                                          how <span class="op">=</span> <span class="st">"proportional"</span>, do.sentence <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> 

<span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">sentimentValues</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">3</span><span class="op">)</span><span class="op">]</span>, <span class="va">head</span>, n <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></code></pre></div>
<pre><code>## $default
##           id       date word_count baseLex--dummyFeature absoluteLex--dummyFeature
## 1: 830982098 1971-01-12        413          -0.009927361                0.09225182
## 2: 830983504 1971-08-04        171          -0.007602339                0.03859649
## 3: 830985611 1971-08-24        280           0.028750000                0.04839286
## 
## $sentences
##           id sentence_id       date word_count baseLex--dummyFeature absoluteLex--dummyFeature
## 1: 830982098           1 1971-01-12         39           -0.04102564                0.06666667
## 2: 830982098           2 1971-01-12         14           -0.03571429                0.03571429
## 3: 830982098           3 1971-01-12         21           -0.07619048                0.07619048</code></pre>
<p>Before going further, we need to aggregate the two last results to a document level sentiment measure. We are going to aggregate sentences using the <code><a href="https://rdrr.io/r/stats/aggregate.html">aggregate()</a></code> function while we will repeat the same operation as before to compute the <em>bins</em> aggregation with the custom weights.</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sentimentValues</span><span class="op">$</span><span class="va">sentences</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="va">sentimentValues</span><span class="op">$</span><span class="va">sentences</span>, 
                                       <span class="fu"><a href="../../reference/ctr_agg.html">ctr_agg</a></span><span class="op">(</span>howDocs <span class="op">=</span> <span class="st">"equal_weight"</span><span class="op">)</span>, do.full <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>

<span class="va">sentimentValues</span><span class="op">$</span><span class="va">bins</span> <span class="op">&lt;-</span> <span class="va">sentimentValues</span><span class="op">$</span><span class="va">bins</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>word_count <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">word_count</span><span class="op">)</span>, 
                                                 <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">.SD</span>, <span class="va">aggregate_bins</span>, w <span class="op">=</span> <span class="va">w</span><span class="op">)</span><span class="op">)</span>,
                                             by <span class="op">=</span> <span class="fu">.</span><span class="op">(</span><span class="va">id</span>, <span class="va">date</span><span class="op">)</span>,
                                             .SDcols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/utils/head.html">tail</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">sentiment</span><span class="op">)</span>, <span class="op">-</span><span class="fl">4</span><span class="op">)</span><span class="op">]</span>

<span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">sentimentValues</span><span class="op">[</span><span class="fl">3</span><span class="op">:</span><span class="fl">4</span><span class="op">]</span>, <span class="va">head</span>, n <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></code></pre></div>
<pre><code>## $sentences
##           id       date word_count baseLex--dummyFeature absoluteLex--dummyFeature
## 1: 830982098 1971-01-12        431           -0.01575727                0.08428384
## 2: 830983504 1971-08-04        173           -0.01753248                0.07046204
## 3: 830985611 1971-08-24        291            0.04249012                0.06012211
## 
## $bins
##           id       date word_count baseLex--dummyFeature absoluteLex--dummyFeature
## 1: 830982098 1971-01-12        419          -0.008185097                0.09232838
## 2: 830983504 1971-08-04        174          -0.005615755                0.03791710
## 3: 830985611 1971-08-24        282           0.022857791                0.04314558</code></pre>
<p>What remains to do is to test our results against the variable <code>s</code> from <code>usnews2</code>. As we know the distribution of positive and negative news in <code>s</code>, we can quickly and in a naive way measure the accuracy by ordering the documents by sentiment values.</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">usnews2</span><span class="op">$</span><span class="va">s</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  -1   1 
## 605 344</code></pre>
<p>We will classify the 605 documents with the lowest sentiment in each measure as negative, and the remaining documents as positive. We add the <code>s</code> variable to the existing measures by merging each of them with <code>usnews2</code>. The use of <code>lapply</code> allows doing this operation for all measures at once. We also order the tables.</p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sentimentValues</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">sentimentValues</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/merge.html">merge</a></span><span class="op">(</span><span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/as.data.table.html">as.data.table</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>, <span class="va">usnews2</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"id"</span>, <span class="st">"s"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span><span class="op">)</span>
<span class="va">sentimentValues</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">sentimentValues</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="va">x</span><span class="op">[</span><span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/setorder.html">order</a></span><span class="op">(</span><span class="va">`baseLex--dummyFeature`</span><span class="op">)</span><span class="op">]</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">sentimentValues</span><span class="op">$</span><span class="va">default</span><span class="op">)</span></code></pre></div>
<pre><code>##           id       date word_count baseLex--dummyFeature absoluteLex--dummyFeature  s
## 1: 830981961 1991-02-21        123           -0.06707317                0.10691057 -1
## 2: 842616972 1989-04-14        206           -0.05412621                0.12305825 -1
## 3: 842616769 2008-03-17        186           -0.05322581                0.08978495 -1
## 4: 842614104 1991-01-02        195           -0.05256410                0.08384615 -1
## 5: 830984835 1996-03-12        175           -0.04942857                0.07228571  1
## 6: 842617451 1988-02-04        159           -0.04874214                0.08270440 -1</code></pre>
<p>Finally, we compute the accuracy by counting the number of times the value of <code>s</code> is -1 in the first 605 documents and the number of times the value is 1 in the last 344 documents. We obtain a balanced accuracy measure by combining the true negative rate (TNR) and the true positive rate (TPR).</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">index</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">usnews2</span><span class="op">$</span><span class="va">s</span><span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span>

<span class="va">rates</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span>
  TNR <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="va">sentimentValues</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">x</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="va">index</span>, <span class="va">s</span> <span class="op">==</span> <span class="op">-</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">x</span><span class="op">[</span>, <span class="va">s</span> <span class="op">==</span> <span class="op">-</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span><span class="op">)</span>,
  TPR <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="va">sentimentValues</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">x</span><span class="op">[</span><span class="op">(</span><span class="fl">1</span> <span class="op">+</span> <span class="va">index</span><span class="op">)</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>, <span class="va">s</span> <span class="op">==</span> <span class="fl">1</span><span class="op">]</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">x</span><span class="op">[</span>, <span class="va">s</span> <span class="op">==</span> <span class="fl">1</span><span class="op">]</span><span class="op">)</span><span class="op">)</span>
<span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">rates</span>, balancedAccuracy <span class="op">=</span> <span class="op">(</span><span class="va">rates</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span> <span class="op">+</span> <span class="va">rates</span><span class="op">[</span>, <span class="fl">2</span><span class="op">]</span><span class="op">)</span> <span class="op">/</span> <span class="fl">2</span><span class="op">)</span></code></pre></div>
<pre><code>##                 TNR       TPR balancedAccuracy
## default   0.7256198 0.5174419        0.6215308
## uShaped   0.7289256 0.5232558        0.6260907
## sentences 0.7256198 0.5174419        0.6215308
## bins      0.7272727 0.5203488        0.6238108</code></pre>
<p>In this case, the U-shaped weighting performs best but we can already see the improvement brought by our custom weights in comparison with the default settings. In a supervised learning setting, it can be useful to optimize a custom weights scheme on a training dataset. An example of such a model can be found in the paper of <a href="https://doi.org/10.1111/fima.12219">Boudt &amp; Thewissen (2019)</a>, where <em>bin</em> weights are optimized to predict firm performance.</p>
</div>
</div>
<div id="bins-of-sentences" class="section level2">
<h2 class="hasAnchor">
<a href="#bins-of-sentences" class="anchor"></a>Bins of sentences</h2>
<p>As we learned in this tutorial, we can always define more complex methods to compute and aggregate sentiment. The reason for using different aggregation levels such as <em>bins</em> or sentences is that words alone do not always capture the semantic structure of the text well. The most appropriate way to compute sentiment is through sentences, as they usually convey a single statement.</p>
<p>Earlier, we implemented the <em>bins</em> approach by creating equal-sized containers of words. Each <em>bin</em> then contains a similar number of words. This naive split has the effect of splitting some sentences across two <em>bins</em>. From a semantic point of view, this is not desirable. Hence, to respect the integrity of the sentences, we propose to use <em>bins</em> of sentences.</p>
<p>This approach is similar to the previous one, but instead of dividing the texts into equal-sized containers of words, we divide them into equal-sized containers of sentences. This means that each <em>bin</em> will contain approximately the same number of sentences.</p>
<p>To implement it, we will need to play a bit with <code>data.table</code> operations to aggregate from sentences to <em>bins</em> of sentences. The first step is to compute sentence sentiment using <code><a href="../../reference/compute_sentiment.html">compute_sentiment()</a></code>. Then, we’re going to add a column to the resulting sentiment object. This additional column will contain information about the future <em>bin</em> in which each sentence will be aggregated. This is a mapping from sentences to <em>bins</em> of sentences.</p>
<p>The following operation creating <code>bin_id</code> is slightly complex. The innermost function here is <code>splitIndices()</code>, which is used to split the <code>sentence_id</code> of each document in equal-sized vectors. The second level, the <code><a href="https://rdrr.io/r/base/lapply.html">sapply()</a></code> function, determines to which split vector belongs each <code>sentence_id</code> and returns boolean vectors for each. Finally, the last <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code> calls the function <code><a href="https://rdrr.io/r/base/which.html">which()</a></code> on each of these vectors, resulting in the correct <em>bin</em> indices.</p>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sentiment</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/compute_sentiment.html">compute_sentiment</a></span><span class="op">(</span><span class="va">usnews2Sento</span>, <span class="va">sentoLexicon</span>, how <span class="op">=</span> <span class="st">"proportional"</span>, do.sentence <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="va">nBins</span> <span class="op">&lt;-</span> <span class="fl">5</span>

<span class="va">sentiment</span> <span class="op">&lt;-</span> <span class="va">sentiment</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span>
  bin_id <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="fu">parallel</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/r/parallel/splitIndices.html">splitIndices</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">sentence_id</span><span class="op">)</span>, <span class="va">nBins</span><span class="op">)</span>, <span class="st">"%in%"</span>, x <span class="op">=</span> <span class="va">sentence_id</span><span class="op">)</span>, 
                 <span class="va">which</span>,
                 MARGIN <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>, 
  <span class="va">.SD</span><span class="op">)</span>, 
  by <span class="op">=</span> <span class="va">id</span><span class="op">]</span>

<span class="va">sentiment</span><span class="op">[</span><span class="va">id</span> <span class="op">==</span> <span class="st">"830981632"</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">6</span><span class="op">]</span></code></pre></div>
<pre><code>##           id bin_id sentence_id       date word_count baseLex--dummyFeature
## 1: 830981632      1           1 1988-04-20         28           -0.09285714
## 2: 830981632      1           2 1988-04-20         37            0.01081081
## 3: 830981632      2           3 1988-04-20          6           -0.01666667
## 4: 830981632      2           4 1988-04-20         33            0.01666667
## 5: 830981632      3           5 1988-04-20         16           -0.04687500
## 6: 830981632      4           6 1988-04-20         24            0.04166667
## 7: 830981632      4           7 1988-04-20         24            0.07708333
## 8: 830981632      5           8 1988-04-20         17           -0.18529412
## 9: 830981632      5           9 1988-04-20         17            0.05000000</code></pre>
<p>With this result, we can now use the new column <code>bin_id</code> for grouping. We cannot use the <strong><code>sentometrics</code></strong> functions here, as they are not built to take into account a <code>bin_id</code> column. Instead, we use a <code>data.table</code> operation similar to what we did to compute the <em>bins</em> aggregation with custom weights. This time, however, we will simply use the <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code> function, meaning that each <em>bin</em> of sentences will contain the average sentiment value of the constituent sentences.</p>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sentiment</span> <span class="op">&lt;-</span> <span class="va">sentiment</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>word_count <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">word_count</span><span class="op">)</span>, 
                           sentence_count <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">sentence_id</span><span class="op">)</span>, 
                           <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">.SD</span>, <span class="va">mean</span><span class="op">)</span><span class="op">)</span>,
                       by <span class="op">=</span> <span class="fu">.</span><span class="op">(</span><span class="va">id</span>, <span class="va">date</span>, <span class="va">bin_id</span><span class="op">)</span>,
                       .SDcols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/utils/head.html">tail</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">sentiment</span><span class="op">)</span>, <span class="op">-</span><span class="fl">5</span><span class="op">)</span><span class="op">]</span>

<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">sentiment</span><span class="op">[</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">6</span><span class="op">]</span><span class="op">)</span></code></pre></div>
<pre><code>##           id       date bin_id word_count sentence_count baseLex--dummyFeature
## 1: 830982098 1971-01-12      1         74              3          -0.050976801
## 2: 830982098 1971-01-12      2         65              3          -0.059879565
## 3: 830982098 1971-01-12      3        110              4          -0.003560228
## 4: 830982098 1971-01-12      4         78              3           0.043204365
## 5: 830982098 1971-01-12      5        104              3          -0.006387387
## 6: 830983504 1971-08-04      1         60              2          -0.019007051</code></pre>
<p>Finally, we can recreate the graphs used for our initial analysis of the intratextual sentiment structure, but using <em>bins</em> of sentences. In this case, there is not much difference with the previous analysis. However, using <em>bins</em> of sentences paves the way to more complex and semantically accurate analyses.</p>
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">sentiment</span><span class="op">[</span>, <span class="fu">.</span><span class="op">(</span>s <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">`absoluteLex--dummyFeature`</span><span class="op">)</span><span class="op">)</span>, by <span class="op">=</span> <span class="va">bin_id</span><span class="op">]</span>, type <span class="op">=</span> <span class="st">"l"</span>,
     ylab <span class="op">=</span> <span class="st">"Mean absolute sentiment"</span>, xlab <span class="op">=</span> <span class="st">"Bin (sentences)"</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="va">sentiment</span><span class="op">$</span><span class="va">`absoluteLex--dummyFeature`</span> <span class="op">~</span> <span class="va">sentiment</span><span class="op">$</span><span class="va">bin_id</span>, ylab <span class="op">=</span> <span class="st">"Absolute sentiment"</span>, 
        xlab <span class="op">=</span> <span class="st">"Bin (sentences)"</span>, outline <span class="op">=</span> <span class="cn">FALSE</span>, range <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span></code></pre></div>
<p><img src="isa_files/figure-html/unnamed-chunk-27-1.png" width="1152"></p>
<p>This is the end of this tutorial. Want to go further? Have a try creating more weird <em>bins</em>… They actually do not have to be of equal size, they can be however desired. Also, keep in mind that we have only covered news articles in this tutorial, which is not representative of all types of texts. Feel free to investigate how sentiment is positioned within different types of documents!</p>
</div>
<div id="acknowledgements" class="section level2">
<h2 class="hasAnchor">
<a href="#acknowledgements" class="anchor"></a>Acknowledgements</h2>
<p>Thanks to Samuel Borms for providing a basis for this tutorial.</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by <a href="https://www.linkedin.com/in/sam-borms">Samuel Borms</a>, <a href="https://ardiad.github.io">David Ardia</a>, <a href="https://www.kevenbluteau.com">Keven Bluteau</a>, <a href="https://linkedin.com/in/krisboudt">Kris Boudt</a>.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  
<script src="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.1/docsearch.min.js" integrity="sha256-GKvGqXDznoRYHCwKXGnuchvKSwmx9SRMrZOTh2g4Sb0=" crossorigin="anonymous"></script><script>
  docsearch({
    
    
    apiKey: '29d61aa2be101325ab9a82514b58064b',
    indexName: 'sentometrics',
    inputSelector: 'input#search-input.form-control',
    transformData: function(hits) {
      return hits.map(function (hit) {
        hit.url = updateHitURL(hit);
        return hit;
      });
    }
  });
</script>
</body>
</html>
